version: "3"

services:
  mongo:
    container_name: db_container
    image: mongo
    restart: always

  project:
    build: .
    ports:
      - "3001:3001"
    environment:
      AWS_REGION: "AWS_REGION"
      ACCESS_KEY_ID: "ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
      BUCKET_NAME: "BUCKET_NAME"
    depends_on:
      - mongo
