version: "3"

services:
  mongo:
    container_name: db_container
    image: mongo
    restart: always

  project:
    build: .
    ports:
      - "3001:3001"
    environment:
      AWS_REGION: "ap-south-1"
      ACCESS_KEY_ID: "AKIARGUHT2T43UB2NQHP"
      AWS_SECRET_ACCESS_KEY: "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"
      BUCKET_NAME: "twitterproj123"
    depends_on:
      - mongo
