version: "3"
services:
  any_name:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "3001:3001"
    link:
      - mongo
  random_container_name:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
